apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    {{- include "caresync.labels" . | nindent 4 }}


automountServiceAccountToken: true
