apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: user-service
    {{- include "caresync.labels" . | nindent 4 }}


automountServiceAccountToken: true
