apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-service-pdb
  namespace: {{ .Values.namespace }}
  labels:
    app: ai-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-service
