# Prod-specific overrides
# Image tags are automatically updated by the CI/CD pipeline on push to main
domain_name: caresync-project.online
waf_acl_arn: "arn:aws:wafv2:us-east-1:664685894054:regional/webacl/CareSync-prod-waf/ccfcc9cd-58c7-4864-9a37-5a0adfddb6d9"
services:
  notificationService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/notification-service
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
  appointmentService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/appointment-service
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
  authService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/auth-service
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
  frontend:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/frontend
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
  userService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/user-service
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
  documentService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/document-service
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
  aiService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/ai-service
    tag: a1979a43c067f89889bdcfa1bddc9aea980e7c7a
