# Prod-specific overrides
# Image tags are automatically updated by the CI/CD pipeline on push to main
domain_name: caresync-project.online
waf_acl_arn: "arn:aws:wafv2:us-east-1:664685894054:regional/webacl/CareSync-prod-waf/7b8050d9-0759-430d-b416-98ebb26a2141"
services:
  notificationService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/notification-service
    tag: prod-b63947bf
  appointmentService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/appointment-service
    tag: prod-b63947bf
  authService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/auth-service
    tag: prod-b63947bf
  frontend:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/frontend
    tag: prod-b63947bf
  userService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/user-service
    tag: prod-b63947bf
  documentService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/document-service
    tag: prod-b63947bf
  aiService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/ai-service
    tag: prod-b63947bf
