# Dev-specific overrides
# These would typically be populated by a CI/CD pipeline
services:
  notificationService:
    tag: v0.0.1-dev.0-dev-bc4cee9b
  appointmentService:
    tag: v0.0.1-dev.0-dev-bc4cee9b
  authService:
    tag: v0.0.1-dev.0-dev-8261f408
  frontend:
    tag: v0.0.1-dev.0-dev-be4e97b1
  userService:
    tag: "v0.0.1-dev.0-dev-bc4cee9b"
  documentService:
    tag: "latest"
  aiService:
    tag: "latest"
