# Prod-specific overrides
# Image tags are automatically updated by the CI/CD pipeline on push to main
domain_name: caresync-project.online
waf_acl_arn: "arn:aws:wafv2:us-east-1:664685894054:regional/webacl/CareSync-prod-waf/bb4d1619-3908-4fcc-a588-971ebcadad31"
services:
  notificationService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/notification-service
    tag: v0.0.3
  appointmentService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/appointment-service
    tag: v0.0.5
  authService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/auth-service
    tag: latest
  frontend:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/frontend
    tag: v0.0.6
  userService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/user-service
    tag: v0.0.1
  documentService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/document-service
    tag: v0.0.4
  aiService:
    repository: 664685894054.dkr.ecr.us-east-1.amazonaws.com/caresync/ai-service
    tag: v0.0.2
