
namespace: caresync-dev
environment: dev
region: us-east-1
awsAccountId: ""
apiBaseUrl: ""
waf_acl_arn: "arn:aws:wafv2:us-east-1:664685894054:regional/webacl/CareSync-dev-waf/2b6d66d0-46a6-4b33-b974-86e62e8282ff"

gateway:
  className: kgateway

secrets:
  name: caresync-app-secrets
  awsSecretName: caresync/app-secrets-dev

services:
  authService:
    repository: caresync/auth-service
    tag: latest
    port: 3001
  userService:
    repository: caresync/user-service
    tag: latest
    port: 3002
  appointmentService:
    repository: caresync/appointment-service
    tag: latest
    port: 3003
  documentService:
    repository: caresync/document-service
    tag: latest
    port: 3004
  notificationService:
    repository: caresync/notification-service
    tag: latest
    port: 3005
  aiService:
    repository: caresync/ai-service
    tag: latest
    port: 3006
  frontend:
    repository: caresync/frontend
    tag: latest
    port: 80
